### ISSUE TITLE
stack traces obscure errors

### ISSUE THREAD

**Issue by bsutton** [DataFoxCo/gocsv#10]
Every error produced by gocsv also dumps a stack trace to the console.

The stack trace is great for debugging but annoying when using the tool and making simple mistakes. It makes it hard to see the actual error message.

It would be nice if the stack trace was suppressed unless a switch (--debug) was added to the command line.

**Comment by aotimme** [comment]
I totally agree. I will put this on the backlog. It will take some time to update, but I like your idea of providing a `--debug` switch to toggle it on.

**Comment by aotimme** [comment]
Actually it wasn't so hard :)

**Comment by bsutton** [comment]
your the man :)
