### ISSUE TITLE
Documentation does't detail how to access duplicate column names

### ISSUE THREAD

**Issue by bsutton** [DataFoxCo/gocsv#12]
The doco doesn't provide any description on how you stipulate a column name when a column names appears in multiple csv files or even if the same column name appears twice in a single file.

For instance I'm 'joining' two files that have a common column name.
The contents of these two columns may be different.
I am looking to run a filter after 'joining' the two files but can't work out how to stipulate the second of the two column names to apply the filter to.

**Comment by aotimme** [comment]
This is tricky.

Currently, as per the section on [Specifying Columns](https://github.com/DataFoxCo/gocsv#specifying-columns):
> When specifying the name of a column, it will match all columns that are exact case-sensitive matches.

When you have multiple columns with the same name, the workaround is to specify the column using its (1-based) index.

There is not currently a way to select a specific occurrence of a column name (first, last, nth, etc.).


Do you have any thoughts on an API to enable selecting a specific occurrence of a column name when there are multiple columns with the same name?
