### ISSUE TITLE
Add new empty columns

### ISSUE THREAD

**Issue by heyrocker** [DataFoxCo/gocsv#16]
I'm in a situation where I want to take an existing CSV and add a few empty columns with specific names for it. The CSV is an inventory of website URLs, and I want to add some columns to it like "Up To Date", "Reviewed", "Delete" etc for an audit spreadsheet. I am currently accomplishing this with --template like so:

`gocsv template -t " " --name "Reviewed"`

but it seems a little hacky to have to specify a value there, when all I really want is a new empty column with a specific name. It would be nice to be able to do something like

`gocsv add --name "Reviewed"`

and be done with it.

Thanks for a great tool!

**Comment by aotimme** [comment]
Good idea! I like `gocsv add`, and it sounds like we could merge in the functionality of the `template` subcommand and eventually deprecate that one.

i.e.
```shell
gocsv template [--name NAME] [--template TEMPLATE]  [--prepend] FILE
```

I'll work on that shortly.
