### ISSUE TITLE
select fails to access first column

### ISSUE THREAD

**Issue by bsutton** [DataFoxCo/gocsv#5]
If I have a csv file such as:

Test file: test.csv
````
cat test.csv
ContactName,EmailAddress
````

Run the following:

````
../gocsv select --columns ContactName test.csv
panic: Could not find header "ContactName"

goroutine 1 [running]:
main.GetIndicesForColumnsOrPanic(0xc42000a240, 0x2, 0x2, 0xc420062550, 0x1, 0x1, 0xffffffffffffffff, 0x1, 0x1)
	/Users/alden/gocsv/src/utils.go:18 +0xc1
main.SelectColumns(0x5b4800, 0xc42000a220, 0xc420062550, 0x1, 0x1)
	/Users/alden/gocsv/src/select.go:106 +0x18d
main.(*SelectSubcommand).Run(0xc42000a160, 0xc42000e180, 0x1, 0x1)
	/Users/alden/gocsv/src/select.go:43 +0x133
main.main()
	/Users/alden/gocsv/src/gocsv.go:96 +0x22d

````

As can be seen the select cannot find the first column.

If I change test.csv to:

````
cat test.csv 
fred,ContactName,EmailAddress
````

Then run

````
../gocsv select --columns ContactName test.csv
ContactName
````
Now that ContactName is the second column the select works.

**Comment by aotimme** [comment]
I am not able to reproduce this. For me:
```shell
$ cat test.csv
ContactName,EmailAddress
$ gocsv select --columns ContactName test.csv
ContactName
```

Are you on the most recent version of `gocsv`?

If you are and you are still getting this error, what OS are you on?

**Comment by bsutton** [comment]
I'm running ubuntu 18.04.
If I use the column index --column 1 then it finds the column.

I downloaded the released file from github.

gocsv doesn't appear to report a version.

**Comment by aotimme** [comment]
I have easy access to a box running Ubuntu 16.04 and it works there. I can try reproducing on ubuntu 18.04 sometime tomorrow.

Two more questions that may help:
1. Does the same issue happen with other subcommands where you want to specify the column? I would assume so, but I just want to verify.
2. Can you attach the `test.csv` file to a comment? I can't imagine it's different from what I made and tried, but just to isolate variables...

And you're right that `gocsv` does not report a version at this time. I am hoping to start appropriately versioning soon, but in the meantime I will add a feature to report the hash of the commit associated with the build of the binary.

**Comment by bsutton** [comment]
[test.txt](https://github.com/DataFoxCo/gocsv/files/2121421/test.txt)

Yes other commands 'unique' fail

````
../gocsv unique --columns fred test.txt
panic: Could not find header "fred"

goroutine 1 [running]:
main.GetIndicesForColumnsOrPanic(0xc42008c450, 0x3, 0x3, 0xc420062550, 0x1, 0x1, 0x8, 0x5b4800, 0xc42000a220)
	/Users/alden/gocsv/src/utils.go:18 +0xc1
main.UniqueifyUnsorted(0x5b4800, 0xc42000a220, 0xc420062550, 0x1, 0x1)
	/Users/alden/gocsv/src/unique.go:175 +0xba
main.(*UniqueSubcommand).Run(0xc42000a1c0, 0xc42000e180, 0x1, 0x1)
	/Users/alden/gocsv/src/unique.go:55 +0x1a1
main.main()
	/Users/alden/gocsv/src/gocsv.go:96 +0x22d
````

**Comment by aotimme** [comment]
It appears that your file contains a UTF-8 BOM which is causing the issue:
```shell
$ cat test.txt
fred,ContactName,EmailAddress
$ file test.txt
test.txt: UTF-8 Unicode (with BOM) text
```
This is a problem because there is a BOM character at the beginning of the file which makes it looks like the first column's header is "fred" but really there are some special characters before "fred" that gocsv assumes are a part of the header.

If I make the same CSV file as a ASCII text file, then `gocsv` has no issue:
```shell
$ cat test-text.txt
fred,ContactName,EmailAddress
$ file test-text.txt
test-text.txt: ASCII text
```

If you do already have a file with a BOM, then one workaround is to remove the first 3 bytes before passing it along to `gocsv`:
```shell
$ tail -c +4 test.txt | gocsv select -c fred
fred
```

I will look more into files containing a UTF-8 BOM to see if it makes sense to either have `gocsv` automatically strip it or to have `gocsv` conserve the BOM when it processes files.

**Comment by aotimme** [comment]
It looks like UTF-8 BOM is the default encoding when exporting a CSV from Excel, so this is likely an issue that will affect many users.

Given that I will (a) add an option to `gocsv clean` to remove the BOM and (b) preserve BOM encoding in CSV outputs when the UTF-8 BOM is detected in input CSVs.

Thanks @AurielleP for the help tracking that down and bringing it to my attention that it's an issue from Excel.

**Comment by bsutton** [comment]
I'm using libreoffice so looks like it is doing the same thing.

**Comment by aotimme** [comment]
As of commit 3e38490955531b46bd9358de36474209b9775286 any BOM that exists in an input will be carried through to the output (unless of course you choose to use the `--strip-bom` argument to `gocsv clean`).

When there are multiple files (e.g. with the `stack` or `join` subcommands), then the logic is to include a BOM in the output if _any_ of the input files has a BOM.

The commit also adds another option to `gocsv clean` (`--add-bom`) to add a BOM to a file (kind of silly, but I see the use case if you get a CSV from one place and want it to render okay in Excel / LibreOffice / etc).
