### ISSUE TITLE
Join semantics not consistent with sql

### ISSUE THREAD

**Issue by bsutton** [DataFoxCo/gocsv#7]
The join syntax doesn't seem to quite match the sql syntax.

When I 'left' join a csv file I'm expecting to only get rows in the left table if and only if they match a row in the right hand table.

In fact I get every row in the left table regardless of whether they are in the right table or not.

This perhaps seems like it might make sense for csv files, but then what does the 'outer' join method do?

**Comment by bsutton** [comment]
It appears that 'right' works however left and outer give the same results:

left.csv
````
dummy,First,Second
d,One,"Tom"
d,Two,"Paul"
d,Three,"Kyle"
````

right.csv

````
dummy,First,Other
d,One,Nurk
d,Two,Smith
````

Left Join

````
../gocsv join --left --columns "First","First" left.csv right.csv
dummy,First,Second,dummy,First,Other
d,One,Tom,d,One,Nurk
d,Two,Paul,d,Two,Smith
d,Three,Kyle,,,

````
Note the third column should not have been output

Right Join - behaves correctly
````
../gocsv join --right --columns "First","First" left.csv right.csv
dummy,First,Second,dummy,First,Other
d,One,Tom,d,One,Nurk
d,Two,Paul,d,Two,Smith
````

Outer Join - behaves correctly and identical to left join

````
./gocsv join --outer --columns "First","First" left.csv right.csv
dummy,First,Second,dummy,First,Other
d,One,Tom,d,One,Nurk
d,Two,Paul,d,Two,Smith
d,Three,Kyle,,,
````

**Comment by bsutton** [comment]
OK, worked it.
Might be a good idea to update the doco given it doesn't reflect standard sql conventions.

So:
left is like an sql 'left outer' join.
right is like an sql 'right outer' join
and
outer is like an sql 'outer' join

**Comment by aotimme** [comment]
Ah yes you're right.

* `--left` is "left outer"
* `--right` is "right outer"
* `--outer` is "full outer" or "outer"

I will update the documentation this evening! Thank you for pointing that out.

**Comment by bsutton** [comment]
well actually don't listen to me. I realised I was being an idiot as I was leaving the office.

left join is a 'left outer join', there is no such thing as a 'left inner join' I was just having a moment.

Having said that I think your doco suggestions are a good idea to remind nuf nuf's like me as to what the semantics are :)

BTW: I'm absolutely loving gocsv. I've been looking for a tool that can do this sort of thing for a long time. So well done!

**Comment by aotimme** [comment]
I added some clarification to the README to make it more obvious.

I'm glad you are getting some good use out of the tool!
