### ISSUE TITLE
Add filter for 'empty' column

### ISSUE THREAD

**Issue by bsutton** [DataFoxCo/gocsv#8]
I've been using left/right outer joins and need to identify rows where the join didn't match.

I can do this with a filter and a regex but that's a bit painful.

It would be nice to have a filter that explicitly matches a blank/empty column.

e.g.

````
gocsv filter --columns a,b --empty

````
I think the semantics of empty should evaluate to true even if the field contains spaces.

**Comment by aotimme** [comment]
Yeah when I have to do something like that I will generally use the regular expression `"^$"` for an empty column. Or if you want blank columns maybe `"^\s*$"` or `"^\W*$" (depending on what you want).

I worry a little that not everyone agrees on what "empty" means (i.e. the only characters are whitespace? tabs? newlines?). So I'd rather have the end user specify what they mean through the regular expression.

**Comment by aotimme** [comment]
I'll add an example to the docs, though. That is definitely a common use case!

**Comment by bsutton** [comment]
There is always a balance between keeping to a minimum useful set of features and usability.

An example will probably be adequate but an explicit option would be nice :)

If you clearly define what 'empty' is defined as and give some regex alternatives you do get the best of both worlds.

my two cents worth :)
