### ISSUE TITLE
Allows spaces between column names for --columns and --names

### ISSUE THREAD

**Issue by bsutton** [DataFoxCo/gocsv#9]
It took me a little while to work out what was going wrong and this may be a little hard to fix.

Essentially I habitually add a space after a comma.
The result for me was that when specifying columns to the --column switch I was getting an error 'too many files'.
I eventually worked out that the --column switch looks for the first space to determine the end of the column list.

This isn't documented and the resulting error was non-obvious.

This either needs to be explicitly documented or the command line changed to deal with spaces.
It looks like change the command line parsing could only be done in a 'non backward compatible' method so it might be better to just highlight this fact in the doco.

**Comment by bsutton** [comment]
I should note that I think the below should work:

gocsv select --columns "Description, Name, Remote, Label, Product, Description" x.csv
panic: Could not find header " Name"

Note the space between the comma and the Name column.

**Comment by aotimme** [comment]
Good call. I just added some references to that issue in the documentation: https://github.com/DataFoxCo/gocsv#specifying-columns. Let me know if that doesn't seem sufficient.
